# fly.toml app configuration file for mailmind
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mailmind"
primary_region = "ord"

[build]

[env]
  PORT = "8080"
  FLASK_ENV = "production"
  MAILMIND_PRODUCTION = "1"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    interval = "10s"
    grace_period = "5s"
    method = "GET"
    path = "/"
    protocol = "http"
    timeout = "2s"

[processes]
  app = "gunicorn --bind 0.0.0.0:8080 --workers 2 --threads 4 --worker-class gthread --timeout 300 --keep-alive 65 app:app"
  scheduler = "python scheduler_run.py"

[http_service.concurrency]
  type = "connections"
  hard_limit = 25
  soft_limit = 20

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
