# fly.toml app configuration file generated for mailmind on 2025-06-04T21:50:51-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mailmind"
primary_region = "ord"

[build]

[env]
  PORT = "8080"
  FLASK_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "10s"
  grace_period = "5s"
  method = "GET"
  path = "/"
  protocol = "http"
  timeout = "2s"

[http_service.concurrency]
  type = "connections"
  hard_limit = 25
  soft_limit = 20

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1