"""Removed link length limit in unsubscribe

Revision ID: 11296ded5140
Revises: 
Create Date: 2025-06-06 16:39:08.317881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11296ded5140'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('unsubscribe', schema=None) as batch_op:
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unsubscribe', schema=None) as batch_op:
        batch_op.alter_column('link',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)

    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.alter_column('link',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
