"""sprint 4 initial schema

Revision ID: 34345d809b8a
Revises: 
Create Date: 2026-07-01 19:33:18.052423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34345d809b8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primary_email', sa.String(length=255), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time', sa.Text(), nullable=True),
    sa.Column('timezone', sa.Text(), nullable=True),
    sa.Column('subscribed', sa.Boolean(), nullable=False),
    sa.Column('temp', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id')
    )
    with op.batch_alter_table('master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_master_primary_email'), ['primary_email'], unique=True)

    op.create_table('email_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('oauth_token', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_account')
    with op.batch_alter_table('master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_primary_email'))

    op.drop_table('master')
    # ### end Alembic commands ###
