"""Added stripe_customer_id to User

Revision ID: 4154471a5224
Revises: 1a78e51fc29a
Create Date: 2025-05-26 13:13:57.762584

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4154471a5224'
down_revision = '1a78e51fc29a'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(), nullable=True))
        batch_op.create_unique_constraint('uq_user_stripe_customer_id', ['stripe_customer_id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_stripe_customer_id', type_='unique')
        batch_op.drop_column('stripe_customer_id')
    # ### end Alembic commands ###