"""Added provider field to User

Revision ID: 444ce6db2f68
Revises: 1ef98a9396bb
Create Date: 2025-06-13 17:33:47.085134

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '444ce6db2f68'
down_revision = '1ef98a9396bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)
    existing_columns = [col['name'] for col in inspector.get_columns('user')]
    with op.batch_alter_table('user', schema=None) as batch_op:
        if 'provider' not in existing_columns:
            batch_op.add_column(sa.Column('provider', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('provider')

    # ### end Alembic commands ###
