"""initial schema

Revision ID: 4eaf0064e35f
Revises: 
Create Date: 2026-07-01 02:26:20.161958

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4eaf0064e35f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('short', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time', sa.Text(), nullable=True),
    sa.Column('temp', sa.Boolean(), nullable=True),
    sa.Column('subscribed', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id')
    )
    with op.batch_alter_table('master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_master_username'), ['username'], unique=True)

    op.create_table('email_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('oauth_token', sa.Text(), nullable=False),
    sa.Column('high_priority', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item', sa.Text(), nullable=True),
    sa.Column('master', sa.Integer(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['master'], ['master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unsubscribe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('sender', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cached_email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('account_email', sa.String(length=120), nullable=True),
    sa.Column('message_hash', sa.String(length=64), nullable=True),
    sa.Column('sender', sa.Text(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('received_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action_items', sa.Text(), nullable=True),
    sa.Column('calendar', sa.Boolean(), nullable=True),
    sa.Column('is_first_of_account', sa.Boolean(), nullable=True),
    sa.Column('todo_id', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['email_account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['master_id'], ['master.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['todo_id'], ['todo.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('master_id', 'account_id', 'message_hash', name='uq_cached_email')
    )
    with op.batch_alter_table('cached_email', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cached_email_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cached_email_fetched_at'), ['fetched_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cached_email_master_id'), ['master_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cached_email_message_hash'), ['message_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_cached_email_received_utc'), ['received_utc'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cached_email', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cached_email_received_utc'))
        batch_op.drop_index(batch_op.f('ix_cached_email_message_hash'))
        batch_op.drop_index(batch_op.f('ix_cached_email_master_id'))
        batch_op.drop_index(batch_op.f('ix_cached_email_fetched_at'))
        batch_op.drop_index(batch_op.f('ix_cached_email_account_id'))

    op.drop_table('cached_email')
    op.drop_table('unsubscribe')
    op.drop_table('todo')
    op.drop_table('email_account')
    with op.batch_alter_table('master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_username'))

    op.drop_table('master')
    op.drop_table('link')
    # ### end Alembic commands ###
