"""Switched oauth otken to not be length restricted

Revision ID: 70975dfc825b
Revises: 444ce6db2f68
Create Date: 2025-06-14 17:53:59.999805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70975dfc825b'
down_revision = '444ce6db2f68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('oauth_token',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('oauth_token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
